version: "3.8"
services:
  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    ports:
      - "4200:4200"
    links:
      - backend
  backend:    
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "3000:3000"
    links:
      - mongodb
  mongodb:
    container_name: mongo
    image: mongo
    environment:
     MONGO_INITDB_ROOT_USERNAME: admin
     MONGO_INITDB_ROOT_PASSWORD: admin
     MONGO_INITDB_DATABASE: mongo-todolist
    ports:
      - "27017:27017"
networks:
      default:
        name: appnetwork