version: "3.8"
services:
  frontend:
    container_name: frontend
    restart: always
    build: 
      context: ./frontend
      labels:
          co.elastic.logs/module: nginx
          co.elastic.logs/fileset.stdout: access
          co.elastic.logs/fileset.stderr: error
    ports:
      - "4200:4200"
    links:
      - backend
  backend:    
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "3000:3000"
    links:
      - mongodb


  mongodb:
    container_name: mongo
    image: mongo
    labels:
      co.elastic.logs/module: mongodb
      co.elastic.logs/fileset.stdout: log
    user: root
    command: ['--logpath', '/var/log/mongodb/mongod.log']
    image: mongo
    environment:
     MONGO_INITDB_ROOT_USERNAME: admin
     MONGO_INITDB_ROOT_PASSWORD: admin
     MONGO_INITDB_DATABASE: mongo-todolist
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
      

#  mongoconnector:
#    container_name: mongoconnector
#    build:
#      context: ./mongo-connector
#    environment:
#      - CONFIG_PATH=/data/config/mongo-connector.conf
#    links:
#      - mongodb
#    volumes:
#      - ./docker/mongoconnector:/data


  mongo_connector:
    image: weflex/mongo-connector:latest
    links:
      - mongodb
    environment:
      - MONGO=mongodb://admin:admin@mongodb:27017/todolist?authSource=admin
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin



networks:
      default:
        name: es_elastic
